package finalproject;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		// -Use the key to decrypt the incoming message from socket s.		
		// -Print out the decrypt String to see if it matches the orignal message.
		
		ObjectInputStream in = new ObjectInputStream(s.getInputStream());//read the key from the client
		Key k=(Key)in.readObject();
		
		Cipher decipher = Cipher.getInstance("DES/ECB/PKCS5Padding"); // use the key to decrypt the message
		decipher.init(Cipher.DECRYPT_MODE, k);
		
		CipherInputStream cipherIn = new CipherInputStream(s.getInputStream(),decipher);
		int res = cipherIn.read(); //read a number of result
		
		StringBuffer DecryptedMessage = new StringBuffer(); // read all the numbers and convert to string
		while(res!=-1)
		{
			DecryptedMessage.append((char)res);
			res = cipherIn.read();
		}
		
		System.out.println("The decypted message is:"+DecryptedMessage); //print out the decrypted message
		
		cipherIn.close();
		in.close();
		server.close();
		
		
	}
}